name: Update GeoIP Database
on:
  workflow_dispatch:
  schedule:
    - cron: '5 4 */7 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install dependencies
        run: |
          git config --global --add safe.directory /github/workspace
          rm -rf vendor/bin
          composer install --no-progress --prefer-dist

      - name: Download and setup database
        run: |
          mkdir input
          wget -O db.zip "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country-CSV&license_key=${{ secrets.MAXMIND_LICENSE_KEY }}&suffix=zip"
          unzip db.zip -d input
          rm db.zip
          mv input/*/*.csv input/ -f
          ls input

      - name: Process database
        run: |
          git config --global --add safe.directory '*'
          php vendor/ayesh/geo-ip-tree-builder/run.php input/GeoLite2-Country-Blocks-IPv4.csv input/GeoLite2-Country-Locations-en.csv data
          git status

      - name: Get current date
        id: date
        run: |
          echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
          echo "Update database ${{steps.date.outputs.date}}"

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Update npm
        run: npm install -g npm@latest

      - name: Update composer and npm package versions
        run: npm --no-git-tag-version version "v1.1.${{steps.date.outputs.date}}"

      - name: Commit and tag if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update database ${{steps.date.outputs.date}}"
          tagging_message: "v1.1.${{steps.date.outputs.date}}"
          branch: main

      - name: "Publish npm releases"
        run: |
          npm publish --provenance --access public
