name: Update GeoIP Database
on:  
  push:
  workflow_dispatch:
  schedule:
    - cron: '5 4 */3 * *'

jobs:
  build:

    strategy:
      matrix:
        php-versions: ['8.2']
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          ref: ${{ github.head_ref }}


      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2.25 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}


      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"


      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-


      - name: Install dependencies
        run: |
          rm -rf vendor/bin
          composer install --no-progress --prefer-dist


      - name: Download and setup database
        run: |
          mkdir input
          wget -O db.zip "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country-CSV&license_key=${{ secrets.MAXMIND_LICENSE_KEY }}&suffix=zip"
          unzip db.zip -d input
          rm db.zip
          mv input/*/*.csv input/ -f
          ls input


      - name: Process database
        run: |
          php vendor/ayesh/geo-ip-tree-builder/run.php input/GeoLite2-Country-Blocks-IPv4.csv input/GeoLite2-Country-Locations-en.csv data
          git status


      - name: Get current date
        id: date
        run: |
          echo "::set-output name=date::$(date +'%Y%m%d')"
          echo "Update database ${{steps.date.outputs.date}}"


      - name: Commit and tag if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        id: commit
        with:
          commit_message: "Update database ${{steps.date.outputs.date}}"
          tagging_message: "v1.1.${{steps.date.outputs.date}}"
          branch: main

